{% set data = load_setup_py_data() %}

package:
  name: zstandard
  version: "{{ data.get('version') }}"

source:
  path: ../../

requirements:
  build:
    - python
    - setuptools
    - {{ compiler('c') }}

  run:
    - python

test:
  requires:
    - pytest

  source_files:
    - tests/

  commands:
    - pytest -v

about:
  home: https://github.com/indygreg/python-zstandard
  license: BSD License
  summary: 'Zstandard bindings for Python'
  license_family: BSD
